services:
  client:
    build: ./client
    command: /bin/sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./client:/usr/src/app/dist
    ports:
      - "5173:5173"
    networks:
      - bun_app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/app_development"
      DJANGO_SETTINGS_MODULE: config.settings
    networks:
      - bun_app_network

  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bun_app_network

  nginx:
    image: nginx:latest
    container_name: bun_app_nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - client
      - server
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bun_app_network

networks:
  bun_app_network:
    driver: bridge

volumes:
  db-data:
