version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod 
    command: /bin/sh -c "npm run build && npm install -g serve && serve -s dist"
    volumes:
      - ./client:/usr/src/app
    ports:
      - "80:80" 
    networks:
      - bun_app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 4
    env_file:
      - ./server/.env.prod
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/app_production"
      DJANGO_SETTINGS_MODULE: app.settings.production
    depends_on:
      - db
    networks:
      - bun_app_network

  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_production
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bun_app_network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificates:/etc/ssl/certs
    networks:
      - bun_app_network

networks:
  bun_app_network:
    driver: bridge

volumes:
  db-data:
