# Generated by Django 4.2.16 on 2024-10-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0003_rename_dividend_rate_companyprofile_payout_ratio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="payout_ratio",
        ),
    ]
