# Generated by Django 4.2.16 on 2024-10-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0004_remove_companyprofile_payout_ratio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="dividend_percentage",
        ),
    ]
