# Generated by Django 4.2.16 on 2024-10-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0008_alter_stockprice_rsi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice",
            name="rsi",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
