# Generated by Django 4.2.16 on 2024-10-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0013_alter_companyfinancials_capital_expenditures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyfinancials",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
