# Generated by Django 4.2.16 on 2024-10-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0015_alter_companyfinancials_cash_from_operations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="business_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="employee_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="founding_year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="market_capitalization",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="outstanding_shares",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
