# Generated by Django 4.2.16 on 2024-10-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="average_trading_volume_10d",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="outstanding_shares",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
