# Generated by Django 4.2.16 on 2024-10-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0005_remove_companyprofile_dividend_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("company_name", models.CharField(max_length=255)),
                ("exchange", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="outstanding_shares",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="companyprofile",
            table="company_info_companyprofile",
        ),
    ]
