# Generated by Django 4.2.16 on 2024-10-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "company_info",
            "0007_delete_companyprofilemodel_alter_stockprice_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice",
            name="rsi",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
