# Generated by Django 4.2.16 on 2024-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0009_alter_stockprice_rsi"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprice",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="StockVolume",
        ),
    ]
