# Generated by Django 4.2.16 on 2024-10-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "company_info",
            "0011_tickerreference_alter_companyfinancials_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="businesssegment",
            table="company_info_business_segment",
        ),
        migrations.AlterModelTable(
            name="companyfinancials",
            table="company_info_company_financials",
        ),
        migrations.AlterModelTable(
            name="companyprofile",
            table="company_info_company_profile",
        ),
        migrations.AlterModelTable(
            name="stockprice",
            table="company_info_stock_price",
        ),
        migrations.AlterModelTable(
            name="tickerreference",
            table="company_info_ticker_reference",
        ),
    ]
