# Generated by Django 4.2.16 on 2024-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0012_alter_businesssegment_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyfinancials",
            name="capital_expenditures",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="debt_to_equity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="ebitda_margin",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="enterprise_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="free_cash_flow",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="gross_profit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="net_debt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="net_debt_to_ebitda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="net_income_loss",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="normalized_ebitda",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="operating_margin",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="roa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="roe",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="stockholders_equity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="total_assets",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="total_liabilities",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyfinancials",
            name="total_revenue",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="BusinessSegment",
        ),
    ]
