# Generated by Django 4.2.16 on 2024-09-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("ticker", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=2)),
                ("currency", models.CharField(max_length=3)),
                ("exchange", models.CharField(max_length=255)),
                ("ipo_date", models.DateField(blank=True, null=True)),
                (
                    "market_capitalization",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "share_outstanding",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=15, null=True
                    ),
                ),
                ("website_url", models.URLField(blank=True, max_length=255, null=True)),
                ("logo_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "finnhub_industry",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
