# Generated by Django 4.2.16 on 2024-09-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyFinancials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("fiscal_year", models.IntegerField()),
                ("total_revenue", models.BigIntegerField(blank=True, null=True)),
                ("normalized_ebitda", models.BigIntegerField(blank=True, null=True)),
                ("stockholders_equity", models.BigIntegerField(blank=True, null=True)),
                ("free_cash_flow", models.BigIntegerField(blank=True, null=True)),
                ("capital_expenditures", models.BigIntegerField(blank=True, null=True)),
                ("total_assets", models.BigIntegerField(blank=True, null=True)),
                ("total_liabilities", models.BigIntegerField(blank=True, null=True)),
                ("gross_profit", models.BigIntegerField(blank=True, null=True)),
                ("net_income_loss", models.BigIntegerField(blank=True, null=True)),
                ("operating_expenses", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Company Financial",
                "verbose_name_plural": "Company Financials",
            },
        ),
    ]
