source "https://rubygems.org"

ruby "3.1.5"

gem "rails", "~> 7.1.3", ">= 7.1.3.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false
gem "devise"
gem "rack-cors"

# bcrypt for password hashing
gem "bcrypt", "~> 3.1.7"

group :development, :test do
  gem "debug", platforms: %i[mri windows]

  # RSpec for testing
  gem "rspec-rails", "~> 6.0.0"

  # FactoryBot for fixtures
  gem "factory_bot_rails"

  # Faker for generating fake data
  gem "faker"

  # RuboCop for linting
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end
