source "https://rubygems.org"

ruby "3.1.5"

gem "rails", "~> 7.1.3", ">= 7.1.3.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false
gem "devise"
gem "rack-cors"
gem "bcrypt", "~> 3.1.7"
gem 'finnhub_ruby', '~> 1.1.19'

group :development, :test do
  # 開発環境とテスト環境でのみ使うgemを指定
  gem 'database_cleaner'
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails", "~> 6.0.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end
